/**
 * IAMPolicyAutopilotClient - Wrapper for iam-policy-autopilot-power tools
 * 
 * This client provides typed wrappers for calling tools from the iam-policy-autopilot-power,
 * which provides:
 * - generate_application_policies - Automatic IAM policy generation from code
 * - generate_policy_for_access_denied - Fix IAM errors automatically
 * - fix_access_denied - Deploy IAM policy fixes
 */

import { PowerClient, PowerToolCall } from '../orchestration/PowerClient';
import type {
  GenerateApplicationPoliciesResponse,
  GeneratePolicyForAccessDeniedResponse,
  FixAccessDeniedResponse,
} from '../types/power-tools';

export class IAMPolicyAutopilotClient {
  private powerClient: PowerClient;
  private readonly powerName = 'iam-policy-autopilot-power';
  private readonly serverName = 'iam-policy-autopilot-mcp';

  constructor(powerClient?: PowerClient) {
    this.powerClient = powerClient || new PowerClient();
  }

  /**
   * Generate IAM policies from application code
   * 
   * Analyzes source code files to identify AWS SDK calls and generates
   * least-privilege IAM policies.
   * 
   * @param sourceFiles - Absolute paths to source files
   * @param account - AWS Account ID
   * @param region - AWS Region
   * @param serviceHints - Optional list of AWS services to filter by
   */
  async generateApplicationPolicies(
    sourceFiles: string[],
    account?: string,
    region?: string,
    serviceHints?: string[],
  ): Promise<GenerateApplicationPoliciesResponse> {
    const call: PowerToolCall = {
      powerName: this.powerName,
      serverName: this.serverName,
      toolName: 'generate_application_policies',
      arguments: {
        SourceFiles: sourceFiles,
        ...(account && { Account: account }),
        ...(region && { Region: region }),
        ...(serviceHints && { ServiceHints: serviceHints }),
      },
    };

    const response = await this.powerClient.callTool<GenerateApplicationPoliciesResponse>(call);

    if (!response.success || !response.data) {
      throw new Error(
        `Failed to generate application policies: ${response.error?.message || 'Unknown error'}`,
      );
    }

    return response.data;
  }

  /**
   * Generate IAM policy to fix an AccessDenied error
   * 
   * Analyzes an AccessDenied error message and generates the specific
   * IAM policy needed to fix it.
   * 
   * @param errorMessage - The AccessDenied error message
   */
  async generatePolicyForAccessDenied(
    errorMessage: string,
  ): Promise<GeneratePolicyForAccessDeniedResponse> {
    const call: PowerToolCall = {
      powerName: this.powerName,
      serverName: this.serverName,
      toolName: 'generate_policy_for_access_denied',
      arguments: {
        ErrorMessage: errorMessage,
      },
    };

    const response =
      await this.powerClient.callTool<GeneratePolicyForAccessDeniedResponse>(call);

    if (!response.success || !response.data) {
      throw new Error(
        `Failed to generate policy for access denied: ${response.error?.message || 'Unknown error'}`,
      );
    }

    return response.data;
  }

  /**
   * Deploy IAM policy fix for an AccessDenied error
   * 
   * Applies the IAM policy generated by generatePolicyForAccessDenied to the
   * appropriate role/user to fix the access denied error.
   * 
   * @param accessDeniedFixPolicy - The IAM policy JSON generated by generatePolicyForAccessDenied
   * @param errorMessage - The original AccessDenied error message
   */
  async fixAccessDenied(
    accessDeniedFixPolicy: string,
    errorMessage: string,
  ): Promise<FixAccessDeniedResponse> {
    const call: PowerToolCall = {
      powerName: this.powerName,
      serverName: this.serverName,
      toolName: 'fix_access_denied',
      arguments: {
        AccessDeniedFixPolicy: accessDeniedFixPolicy,
        ErrorMessage: errorMessage,
      },
    };

    const response = await this.powerClient.callTool<FixAccessDeniedResponse>(call);

    if (!response.success || !response.data) {
      throw new Error(
        `Failed to fix access denied: ${response.error?.message || 'Unknown error'}`,
      );
    }

    return response.data;
  }

  /**
   * Complete workflow: Generate and deploy IAM policy fix for AccessDenied error
   * 
   * This is a convenience method that combines generatePolicyForAccessDenied
   * and fixAccessDenied into a single operation.
   * 
   * @param errorMessage - The AccessDenied error message
   * @returns The fix result including policy name and role ARN
   */
  async generateAndFixAccessDenied(errorMessage: string): Promise<FixAccessDeniedResponse> {
    // Step 1: Generate policy
    const policyResponse = await this.generatePolicyForAccessDenied(errorMessage);

    // Step 2: Deploy policy
    const fixResponse = await this.fixAccessDenied(
      JSON.stringify(policyResponse.policy),
      errorMessage,
    );

    return fixResponse;
  }
}
